In [ ]:
# basic imports

import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Modelling
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn. neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

In [2]:
df = pd.read_csv('data/raw.csv')

In [3]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Preparing X and Y variable

x Variable

In [7]:
x = df.drop('math score', axis = 1)
x.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

y variable

In [8]:
y = df['math score']
y.head()

0    72
1    69
2    90
3    47
4    76
Name: math score, dtype: int64

In [9]:
print("Categories in 'gender' column:  ", end= " ")
print(df['gender'].unique())
print(("Categories in 'race/ethnicity' column:  "), end= " ")
print(df['race/ethnicity'].unique())    
print("Categories in 'parental level of education' column:  ", end= " ")
print(df['parental level of education'].unique())       
print("Categories in 'lunch' column:  ", end= " ")
print(df['lunch'].unique())

Categories in 'gender' column:   ['female' 'male']
Categories in 'race/ethnicity' column:   ['group B' 'group C' 'group A' 'group D' 'group E']
Categories in 'parental level of education' column:   ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']
Categories in 'lunch' column:   ['standard' 'free/reduced']

In [ ]:
num_features = ['reading score', 'writing score', 'average_score']
cat_features = ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course'] 

# Encode categorical features
label_encoders = {}